apiVersion: 1

datasources:
  - name: Loki
    type: loki
    uid: loki
    url: http://loki:3100
    access: proxy
    isDefault: true
    jsonData: {}

  - name: Prometheus
    type: prometheus
    uid: prometheus
    url: http://prometheus:9090
    access: proxy
    isDefault: false
    jsonData:
      cacheLevel: Medium
      httpMethod: GET
      prometheusType: Prometheus
      prometheusVersion: 2.50.1

  - name: "Tempo"
    type: tempo
    uid: tempo
    url: http://tempo:3200
    access: proxy
    isDefault: false
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: prometheus
      streamingEnabled:
        metrics: true
        search: true
      tracesToLogsV2:
        customQuery: false
        datasourceUid: loki
      tracesToMetrics:
        datasourceUid: prometheus

  # - name: Mimir
  #   type: prometheus
  #   access: proxy
  #   orgId: 1
  #   url: http://mimir:8080/prometheus
  #   version: 1
  #   editable: true
  #   jsonData:
  #     httpHeaderName1: "X-Scope-OrgID"
  #     secureJsonData:
  #       httpHeaderValue1: "demo"
  #   isDefault: false

  - name: Pyroscope
    uid: local-pyroscope
    type: grafana-pyroscope-datasource
    url: http://pyroscope:4040
    jsonData:
      keepCookies: [pyroscope_git_session]
