receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317" # Change from localhost to 0.0.0.0
      http:
        endpoint: "0.0.0.0:4318" # Change from localhost to 0.0.0.0

extensions:
  health_check:
    endpoint: 0.0.0.0:13133

processors:
  batch:
  # transform:
  #   log_statements:
  #     - context: log
  #       statements:
  #         - set(body, ParseJSONOrDefault(body, body))

exporters:
  otlp:
    endpoint: tempo:4317 # Send traces to Tempo
    tls:
      insecure: true

  otlp/jaeger:
    endpoint: jaeger:4317 # Send traces to Tempo
    tls:
      insecure: true

  prometheus:
    endpoint: "0.0.0.0:9464" # Expose Prometheus metrics

  loki:
    endpoint: http://loki:3100/loki/api/v1/push # Send logs to Loki

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp, otlp/jaeger]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki]
